function Params = MakeParamsStructSA(x)
Params = struct('alpha',x(1),'beta',x(2),'EfieldOffset',x(3),...
		'mu', x(4), 'phiStatic',x(5),...
		'coordNum',x(6));
fprintf('Params: alpha = %f\tbeta = %f\tgamma = %f\tmu = %f\n',x(1),x(2), ...
	x(3),x(4));
fprintf('Params: phiSt = %f\t Z = %f\t',x(5),x(6));
