function Params = MakeParamsStructSA(x)
Params = struct('alpha',x(1),'beta',x(2),'EfieldOffset',x(3),'phiStatic',x(4),...
		'surfAreaConstant',x(5),'NPoffset',x(6));
fprintf('Params: alpha = %f\tbeta = %f\tgamma = %f\n',x(1),x(2), ...
	x(3));
fprintf('Params: phiSt = %f\t A = %f\tB = %f\n',x(4),x(5), ...
	x(6));
