function phi = getAsymmetricGBReactionPotential(xyzSrc, RSrc, ...
							RtildeSrc, ...
							qSrc, xyzDest, ...
							RDest, ...
							RtildeDest, ...
							epsIn, ...
							epsOut)

r_ij = norm(xyzSrc-xyzDest);
f_GB_CHA = sqrt(r_ij^2 + RtildeSrc*RtildeDest*exp(-r_ij^2/(4*RSrc* ...
						  RDest)));
phi = -1 * (1/epsIn - 1/epsOut) * qSrc / f_GB_CHA;
