function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Jul-2014 10:29:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1.5 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-800 -200]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[1 0 0],'DisplayName','q = -1');
set(plot1(2),'LineStyle','--','Color',[0 0 1],'DisplayName','q = +1');

% Create xlabel
xlabel('R_{ion}','FontSize',16);

% Create ylabel
ylabel('Charging free energy (kJ/mol)','FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.718617620549796 0.169011942316358 0.15904686795854 0.110731185218567]);

% Create line
annotation(figure1,'line',[0.175 0.176785714285714],...
    [0.110904761904762 0.916666666666667]);

% Create line
annotation(figure1,'line',[0.439285714285714 0.439285714285714],...
    [0.110904761904762 0.923809523809524]);

% Create doublearrow
annotation(figure1,'doublearrow',[0.182142857142857 0.183928571428571],...
    [0.672809523809524 0.442857142857143]);

% Create doublearrow
annotation(figure1,'doublearrow',[0.448214285714286 0.448214285714286],...
    [0.777571428571429 0.678571428571429]);

% Create textbox
annotation(figure1,'textbox',...
    [0.178571428571428 0.125190476190477 0.21875 0.0571428571428571],...
    'String',{'Radius of sodium ion'});

% Create textbox
annotation(figure1,'textbox',...
    [0.451785714285714 0.260904761904762 0.224107142857143 0.0571428571428571],...
    'String',{'Radius of chloride ion'});

% Create textbox
annotation(figure1,'textbox',...
    [0.451785714285714 0.549000000000001 0.183035714285714 0.123809523809524],...
    'String',{'~100 kJ/mol','VS','MD: ~170 kJ/mol'});

% Create textbox
annotation(figure1,'textbox',...
    [0.191071428571428 0.568047619047621 0.183035714285714 0.123809523809524],...
    'String',{'~190 kJ/mol','VS','MD: ~340 kJ/mol'});

